### ISSUE TITLE
Document queue.length

### ISSUE THREAD

**Issue by loilo** [diamondio/better-queue#35]
When using `better-queue`, I needed to check if there are remaining items in the queue (couldn't rely on the `drain` event). I considered tracking pushed and finished/failed tasks, but I discovered the `length` property in the library's source. It works fine, however it is not documented.

I'd love to see the property nailed down in the readme, mainly to make it a breaking change when it'd be renamed or removed. (To be in line with the rest of the API, an accessor method like `getRemainingCount()` would actually be more fitting. However, the `length` property is already there. Also, even more importantly, it is a very common JavaScript convention.)

I would be happy to attach a PR if there are no objections against the idea?

**Comment by leanderlee** [comment]
I think length is not reliable, in particular if you plan on using a persistent DB store and have multiple consumers taking tasks... the length doesn't increment/decrement properly. The only reliable way to get the count would be to ask the store (it provides upon connect). We could implement an accurate `getRemainingCount` by creating a new (temporary) store connection and disconnecting it immediately.

PRs are welcome!

**Comment by Loilo** [comment]
Yes, I already noticed that using the `length` didn't yield the accurate results I needed to have. (For my solution, I tracked my pushes and finish/fail events instead.)

I didn't close this issue because I was curious what the `length` property actually is about — so thanks for clarifying. :)

I'm not sure if connecting to a store would be all that useful for cases like mine – that sounds like such a method would have to be asynchronous. However, the whole point of wanting to use the `length` is that I needed to check if the queue is empty *at the exact given moment*, which would not be doable with an asynchronous method.

**Comment by leanderlee** [comment]
Another way you can do this is by listening to the `drain` event and keeping track of whether or not items have been pushed in -- that might be a better solution.

**Comment by Loilo** [comment]
Yes, I just thought about that (setting a flag with `drain` and `task_queued`). Should work as well.

I also just realized that, for my case, an async method would actually be fine. The concrete issue was that I had to wait for an external event and then wait for the queue to drain. However, the queue might already be empty, so no `drain` event would ever be fired again. On the other hand, listening for earlier `drain`s wouldn't guarantee that no more items had been pushed in after that.

However, as you mentioned, weighing `drain` vs `task_queued` sounds like it should work and sounds reasonably easy to use.
