### ISSUE TITLE
Blocking HTTP Request 

### ISSUE THREAD

**Issue by xJoeyv** [diamondio/better-queue#64]
The api receives 3mb of logs pushed to the push uri. This data will be added to the queue but does push wait till it is finished? Cause my api reponse will not accur?
```

    const APP_LOG = req.params.app.toLowerCase();
    let BODY: String = req.body;
    if (BODY.endsWith(";;")) {
        BODY = BODY.trim();
        BODY = BODY.substring(0, BODY.length - 2);
    }
    let lines = BODY.split(";;");

    que.push({
        app: APP_LOG,
        lines
    });
```

And for my queue:
```
let que = new BetterQueue(async function (input, cb) {
    console.time(`Queue`);
// Here I put the logs in the DB
    console.timeEnd(`Queue`);
    cb();
});
```

**Comment by nmargaritis** [comment]
This probably does not have to do with better-queue. Try to call this `cb();` in either the http request callback or promise.then depending on what you are using.

```
request.post({url:'http://service.com/upload', formData: formData}, function optionalCallback(err, httpResponse, body) {
  if (err) {
    return console.error('upload failed:', err);
  }
  console.log('Upload successful!  Server responded with:', body);
  cb(); // <-----------------------------
});
```

**Comment by xJoeyv** [comment]
I mean that the post request waits the the queue is done. 
```
$request = curl_init();

        curl_setopt_array($request, [
            CURLOPT_PORT => 3030 ,
            CURLOPT_URL => $this->destination,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_TIMEOUT => 30,
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST => "POST",
            CURLOPT_POSTFIELDS => $textBody,
            CURLOPT_HTTPHEADER => [
                "content-type: text/plain"
            ]
        ]);

        $response = curl_exec($request);
        $err = curl_error($request);
        curl_close($request);

        if ($err != "") {
            throw new \ErrorException("CURL Error: " . $err);
            return;
        }

        $statusJson = json_decode($response);
        if ($statusJson->status != "PUSHED") {
            throw new \ErrorException("Field pushing logs to server: " . $statusJson->data);
            return;
        }
```

**Comment by nmargaritis** [comment]
> I mean that the post request waits till the queue is done
This is again not related with better-queue. 

It is an implementation detail.

Your endpoints should not wait for the queue to process the task, otherwise you are not really using the queue. 

A practice that is followed is that; for long tasks, you return 202 Accepted as a status code with a ticketId (the ticketid is returned from better queue upon creation of task). Then you can store this ticket id somewhere and know when tasks are done or not, at a later point, but your request only wait for the ticketId and not the actual processing.

**Comment by xJoeyv** [comment]
@nmargaritis How should I do that? This is the function behind the API Route:
```Javascript
if (req.params.app == undefined) {
        return res.json({
            status: "MISSING_DATA",
            message: "Missing app name for logs"
        });
    }

    const APP_LOG = req.params.app.toLowerCase();
    let BODY: String = req.body;
    if (BODY.endsWith(";;")) {
        BODY = BODY.trim();
        BODY = BODY.substring(0, BODY.length - 2);
    }
    let lines = BODY.split(";;");

    que.push({
        app: APP_LOG,
        lines
    });

    return res.json({
        status: "PUSHED",
        data: {
            lines: lines.length
        }
    });
```

**Comment by nmargaritis** [comment]
@xJoeyv In the given example, you are not waiting for the queue to finish processing as you were previously suggesting. 

You are just pushing a task to it**. Your logic of parsing body is what causes your API response to be slow.**

Note that these issues on GitHub are related with a node module and its problems Since your problems are not related with better-queue, **please use the appropriate means if you have such questions**, such as stackoverflow.

**Comment by xJoeyv** [comment]
Alright thanks! Issue can be closed!
